# Generated by Django 2.2.12 on 2021-06-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='meal_id',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
